### ISSUE TITLE
Unused/undefined config file change requested by this plugin (trivial issue)

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#59] opened 2020-04-26 15:43 UTC
# Description

The following line in `plugin.xml` is useless (https://github.com/CleverTap/clevertap-cordova/blob/2.1.8/plugin.xml#L67):

```xml
<config-file>
    <access origin="*.wzrkt.com" />
</config-file>
```

Same for `iOS`.

This result in warning:

`config file undefined requested for changes not found at /Users/shashank/Projects/demo-app/platforms/android/undefined, ignoring`.

# Environment

```bash
Ionic:

   Ionic CLI          : 6.5.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res (update available: 0.13.0) : 0.5.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/shashank/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by sagrawal31** [comment] 2020-04-27 09:07
Duplicate of #55

**Comment by darshanclevertap** [comment] 2020-04-30 16:37
@sagrawal31 As you've mentioned duplicate of #55 so closing this.

**Closed by darshanclevertap** 2020-04-30 16:37 UTC

**Comment by sagrawal31** [comment] 2020-04-30 16:42
Thanks @darshanclevertap
